### ISSUE TITLE
Grabbed blocks don't seem to trigger block updates

### ISSUE THREAD

**Issue by cosmicdan** [HostileNetworks/weather2#1]
E.g. When farmland is grabbed, a crop that was on that farmland remains - it doesn't "pop-out" until a block update is triggered some other way. Might be specific to HarvestCraft crops, unsure.

**Comment by Dulciphi** [comment]
Not specific to harvestcraft crops. I've noticed the same thing when using the cofh/clearblocks command, too. Even some of the long grasses and snow tiles remain, having to be 'disturbed' before they'll 'pop-out'. I also figured it was something to do with block updates but what (if anything) could be done about it, I don't know

**Comment by cosmicdan** [comment]
Already does notify neighbors. Not a Weather2 bug.
